config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }
  resources :users
  resources :products, :invoices, :orders, :users # 5.1 added ", :invoices, :orders, :users"
  resources :users, except: [:index]
  get 'simple_pages/about'
  get 'simple_pages/contact'
  get 'simple_pages/index'
  get 'simple_pages/landing_page'
  post 'simple_pages/thank_you'
  post 'payments/create'
  root 'simple_pages#landing_page'
  mount ActionCable.server => '/cable'


  resources :products do # 5.8 added
    resources :comments
  end

  resources :products do
     resources :payments
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :comments

  validates :name, presence: true

  def self.search(search_term)
    if RAILS.environment.production?
      Product.where("name LIKE ? OR colour LIKE ? OR description LIKE ?", "%#{search_term}%", "%#{search_term}%", "%#{search_term}%")
    else
      Product.where("name ilike ?", "%#{search_term}%")
    end

  end

  def highest_rating_comment
    comments.rating_desc.first
  end

  def lowest_rating_comment
    comments.rating_desc.last
  end

  def average_rating
    comments.average(:rating).to_f
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    if params[:q]
      search_term = params[:q]
      @products = Product.search(search_term)
      logger.debug "My search found #{@products.count} products"
      if @products.nil?
        flash.now[:notice] = "Hey we don't have #{search_term}, check out our other products"
      end
    else
      @products = Product.all
      logger.debug "My search found #{@products.count} products"
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @comments = @product.comments.order("created_at DESC").paginate(:page => params[:page], :per_page => 2)
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to "/simple_pages/landing_page", notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :colour, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
  def cache_key_for_products
    count          = @products
    max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "products/all-#{count}-#{max_updated_at}"
  end
end

app/views/products/_comments.html.erb
<div class="product-reviews">
    <% @comments.each do |comment| %>
      <%= render comment %>
    <% end %>
</div>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %><br>
    <%= form.text_field :name, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= form.label :description %><br>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :image_url %><br>
    <%= form.text_field :image_url, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :color %><br>
    <%= form.text_field :color, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :price %><br>
    <%= form.text_field :price, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_new_comment.html.erb
<% if signed_in? %>
<br>
  <div class="row">
    <h4>Add a review:</h4>
      <%= form_for([@product, @product.comments.build], remote: true) do |f| %>
  </div> <!-- end row -->

  <div class="form-group row">
    <%= f.label :body, "Comments" %><br>
    <%= f.text_area :body, class: "form-control" %>
  </div>

  <div class="form-group row">
    <%= f.label :rating %><br>
    <%= f.text_field :rating, class: "rating form-control" %>
  </div>  

  <div class="row">
    <p>
      <div class="rating"></div>
    </p>

    <p>
      <%= f.submit "Submit" %>
    </p>
  </div>


  <% end %>
<% end %>

app/views/products/_product.html.erb
<div class="col-xl-3 col-md-4 col-sm-12">
<% cache product do %>

  <%= link_to product do %>
    <% if product.image_url %>
      <%= image_tag(product.image_url, class: "img-thumbnail img-fluid") %>
    <% end %>
  <h2><%= product.name %></h2>
  <% end %>

  <p><strong>Product Description: </strong><%= product.description %></p>
  <p><strong>Color: </strong><%= product.colour %></p>
  <p><strong>Price: </strong><%= product.price %></p>
  <!-- may add these back in for logged in admin 
  <%= link_to 'Show', product, class:"btn btn-primary" %>
  <%= link_to 'Edit', edit_product_path(product), class:"btn btn-info" %>
  <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
-->
<% end %>

</div><!-- /col -->

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<!-- may add in for logged in admin
<%= link_to 'New Product', new_product_path, class:"btn btn-info" %>
-->

<br>
<br> 
<%= link_to 'Questions?', simple_pages_contact_path, class:"btn btn-primary" %>
<br>
<br>

  <div class="row">
    <% cache(cache_key_for_products) do %>
      <%= render @products %>
    <% end %>
  </div> 

app/views/products/new.html.erb
    <h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-xs-12">
    <% cache @product do %>
    <p>
      <%= @product.name %>
    </p>
    <% end %>
  </div> <!--end col-->
</div> <!--end row-->

<div class="row">
  <div class="col-xs-12">
    <p>
      <%= image_tag(@product.image_url, class: "img-fluid img-zoom img-responsive", data_zoom_image: @product.image_url)%>
    </p>
  </div> 
</div>

<div class="row" data-product-id="<%= @product.id %>">
  <div class="col-xs-12">
    <p>
      <%= @product.description %>
    </p>
  </div>
</div>

<div class="row">
  <div class="col-xs-12">
    <p>
      <strong>Color:</strong>
      <%= @product.colour %>
    </p>
  </div>
</div>

<div class="row">
  <div class="col-xs-12">
    <p><strong>Average Rating: </strong> <div class="rated" id="average-rating" data-score="<%= @product.average_rating %>"></div> </p>
  </div>
</div>

<div class="row">
  <div class="col-xs-12">
    <p>
      <%= number_to_currency(@product.price) %>
    </p>
    <p>
      <%= form_with(url: '/payments/create') do |form| %>
      <%= form.hidden_field :product_id, :value => @product.id %>
      <%= render partial: "shared/stripe_checkout_button" %>
    </p>
<% end %>
  </div>
</div>



<div class="row">
  <div class="col-xs-12">
    <%= @product.highest_rating_comment&.body %>
  </div>
</div>

<div class="row">
  <div class="col-xs-12">
    <%= link_to 'Edit', edit_product_path(@product), class: 'btn btn-primary' %> 
  </div>
</div>

<br>

<div class="row">
  <div class="col-xs-12">
    <%= link_to 'Back', products_path, class: 'btn btn-info' %>
  </div>
</div> <!-- end row -->

<div class="alert alert-info" style="display:none" role="alert">A new comment was posted!</div>
<%= render 'new_comment' %>
<%= render 'comments' %>

<div class="digg_pagination">
<%= will_paginate @comments, :page_links => false  %>
</div>